{
  try {
    validate(string);
    fail("Should have failed");
  }
 catch (  IllegalArgumentException e) {
  }
}
