{
  try {
    return method.invoke(delegate,args);
  }
 catch (  InvocationTargetException e) {
    throw e.getCause();
  }
}
