{
  manager.newUser("jake","abc123",true);
  try {
    manager.deleteUser("nonExistentUser");
    TestCase.fail("User 'nonExistentUser' should no longer exist, expected exception.");
  }
 catch (  InvalidArgumentsException e) {
    assertThat(e.getMessage(),containsString("User 'nonExistentUser' does not exist."));
  }
catch (  Throwable t) {
    assertThat(t.getClass(),IsEqual.equalTo(InvalidArgumentsException.class));
  }
  assertNotNull(users.getUserByName("jake"));
}
