{
  try {
    db.getRelationshipById(id);
    fail("Exception expected");
  }
 catch (  Exception e) {
    assertThat(e,instanceOf(NotFoundException.class));
  }
}
