{
  try {
    log.error(msg,exception);
    return exception;
  }
 catch (  Throwable t) {
    return exception;
  }
}
