{
  if (failure != null) {
    throw new IOException("An earlier force has failed",failure);
  }
  return true;
}
