{
  IOException exception=new IOException();
  stub(wrapped.postVisitDirectory(any(),any())).toThrow(exception);
  try {
    throwExceptions(wrapped).postVisitDirectory(null,exception);
    fail("Expected exception");
  }
 catch (  Exception e) {
    assertThat(e,is(exception));
  }
}
