{
  for (  Synchronization s : syncHooks) {
    try {
      s.afterCompletion(status);
    }
 catch (    Throwable t) {
      log.warning("Caught exception from tx syncronization[" + s + "] afterCompletion()");
    }
  }
  syncHooks=null;
}
