{
  final IOException ioex=new IOException();
  when(terms.next()).thenThrow(ioex);
  try {
    accessor.sampleIndex(Registers.newDoubleLongRegister());
    fail("should have thrown");
  }
 catch (  RuntimeException ex) {
    assertSame(ioex,ex.getCause());
  }
}
